### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by uriid1** [uriid1/tnt-tg-bot#5]
- [x] Переработать систему событий. Стоит обрабатывать только одно событие - получены новые данные, а остальные подключать уже в логике приложения.
- [x]  Добавить новых классов
   - [x] Для обработке платежей в звездах.
- [x] Переписать логику классов, методы могут быть зависимы от конкретного класса
- [x] Мигрировать на последнюю стабильную версию tarantool
   - [x] В [install-dependencies.sh](https://github.com/uriid1/tnt-tg-bot/blob/main/install-dependencies.sh) необходимо будет заменить `tarantooctl` на `tt`
- [x] Сделать процесс для обработки команд `processes/processCommand.lua`
- [x] Упросить отправку изображений через `bot.sendImage`
- [x]  /libs для библиотек
- [x] в /libs добавить `parseInitData`
- [x] /extensions - переименовать в /ext
- [x] html_formatter.lua сократить имя до hdec. И вообще это декоратор а не форматтер.
- [x] В readme описать как можно подробнее работу библиотеки.
- [x] Добавить разных примеров в /examples, для этого придется скорее всего переделать файловую структуру библиотеки
    - [x] Пример с ручками
    - [x] Пример с инлайн кнопками
    - [x] Пример с отправкой разных медиа файлов
